apiVersion: batch/v1
kind: Job
metadata:
  name: znuny-kaniko-build
  namespace: default
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          command:
            - sh
            - -c
            - |
              git clone https://aschiffler:$(GH_TOKEN)@github.com/aschiffler/znuny-k8s.git /workspace
              ls /workspace/docker/
          env:
            - name: GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: znuny-build-secret
                  key: github-token
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --dockerfile=/workspace/docker/Dockerfile
            - --context=/workspace/docker
            - --destination=10.152.183.235:5000/znuny:7.3
            - --destination=10.152.183.235:5000/znuny:latest
            - --insecure
            - --skip-tls-verify
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
