---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: znuny
    service: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodeport }}
  selector:
    instance: {{ .Release.Name }}-{{ .Release.Namespace }}


