DEFAULT_ZNUNY_TIMEZONE="Etc/UTC"

DEFAULT_ZNUNY_SECURE_MODE="1"

DEFAULT_APP_USER="znuny"

DEFAULT_ZNUNY_DATABASE_HOST="localhost"
DEFAULT_ZNUNY_DATABASE_PORT="5432"
DEFAULT_ZNUNY_DATABASE_NAME="znuny"
DEFAULT_ZNUNY_DATABASE_USER="znuny"
DEFAULT_ZNUNY_DATABASE_PASSWORD="password"

DEFAULT_ZNUNY_APACHE_DOMAIN="_default_"

DEFAULT_ZNUNY_USER_ADMIN_NAME="root@localhost"
DEFAULT_ZNUNY_USER_ADMIN_PASSWORD="password"

DEFAULT_ZNUNY_MAILING_TYPE="sendmail"

DEFAULT_ZNUNY_CONFIGURATIONS_OVERRIDES_DIRECTORY="/overrides"
